coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 60%

ignore:
  - "astronomer_starship/_af2/cutover.py"
  - "astronomer_starship/_af2/starship.py"
