services:
  webserver:
    volumes:
      - $PWD/../:/usr/local/airflow/starship:rw
    command: >
        bash -c 'if [[ -z "$$AIRFLOW__API__AUTH_BACKEND" ]] && [[ $$(pip show -f apache-airflow | grep basic_auth.py) ]];
          then export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth ;
          else export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default ; fi &&
          { airflow users create "$$@" || airflow create_user "$$@" ; } &&
          { airflow sync-perm || airflow sync_perm ;} &&
          airflow webserver -d' -- -r Admin -u admin -e admin@example.com -f admin -l user -p admin
