name: Check
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: j178/prek-action@v1

  test_legacy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Run tests
        run: uvx --python 3.12 --with tox-uv tox -e 3.7-af20

  test:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      # - uses: actions/setup-python@v6
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
      - name: Run tests
        run: uvx --with tox-uv tox p
