name: CI
on: [push]
jobs:
  ship-package-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          astronomer-starship-provider:
            - 'astronomer-starship-provider/**'
          astronomer-starship:
            - 'astronomer-starship/**'
            
    # run only if 'astronomer-starship' was changed
    - name: astronomer-starship
      if: steps.filter.outputs.astronomer-starship == 'true' && startsWith(github.ref, 'refs/tags/astronomer-starship-v')
      run: |
        make install_dev
        cd ${GITHUB_WORKSPACE}/astronomer-starship
        make build
        make ship
      env:
        TWINE_USER: "__token__"
        TWINE_PASS: ${{ secrets.TWINE_PASS_ASTRONOMER_STARSHIP }}

    # run only if 'astronomer-starship-provider' was changed
    - name: astronomer-starship-provider
      if: steps.filter.outputs.astronomer-starship-provider == 'true' && startsWith(github.ref, 'refs/tags/astronomer-starship-provider-v')
      run: |
        make install_dev
        cd ${GITHUB_WORKSPACE}/astronomer-starship-provider
        make build
        make ship
      env:
        TWINE_USER: "__token__"
        TWINE_PASS: ${{ secrets.TWINE_PASS_ASTRONOMER_STARSHIP_PROVIDER }}
